# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_poverki.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 714)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 160, 1041, 471))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(20, 60, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setObjectName("textEdit")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_3.setGeometry(QtCore.QRect(20, 320, 191, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_3.setMouseTracking(False)
        self.spinBox_3.setTabletTracking(False)
        self.spinBox_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinBox_3.setWhatsThis("")
        self.spinBox_3.setAccessibleName("")
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_3.setProperty("showGroupSeparator", False)
        self.spinBox_3.setMinimum(1917)
        self.spinBox_3.setMaximum(2060)
        self.spinBox_3.setObjectName("spinBox_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 641, 161))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 30, 621, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(430, 50, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setLineWidth(1)
        self.label_15.setMidLineWidth(1)
        self.label_15.setObjectName("label_15")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setLineWidth(1)
        self.label_12.setMidLineWidth(1)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(220, 50, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setLineWidth(1)
        self.label_14.setMidLineWidth(1)
        self.label_14.setObjectName("label_14")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_5.setGeometry(QtCore.QRect(430, 90, 181, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_5.setFont(font)
        self.textEdit_5.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_5.setPlaceholderText("")
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 90, 181, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_3.setFont(font)
        self.textEdit_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_4.setGeometry(QtCore.QRect(220, 90, 181, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_4.setFont(font)
        self.textEdit_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_4.setUndoRedoEnabled(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(250, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(250, 60, 391, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_2.setFont(font)
        self.textEdit_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_2)
        self.dateEdit.setGeometry(QtCore.QRect(20, 60, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 7, 8), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(440, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(230, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 290, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 120, 641, 141))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(10, 30, 621, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setLineWidth(1)
        self.label_16.setMidLineWidth(1)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(220, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setLineWidth(1)
        self.label_17.setMidLineWidth(1)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(430, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAutoFillBackground(False)
        self.label_18.setLineWidth(1)
        self.label_18.setMidLineWidth(1)
        self.label_18.setObjectName("label_18")
        self.textEdit_7 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_7.setGeometry(QtCore.QRect(10, 100, 191, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_7.setFont(font)
        self.textEdit_7.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_7.setPlaceholderText("")
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_8 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_8.setGeometry(QtCore.QRect(220, 100, 181, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_8.setFont(font)
        self.textEdit_8.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_9 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_9.setGeometry(QtCore.QRect(430, 100, 181, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_9.setFont(font)
        self.textEdit_9.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_9.setPlaceholderText("")
        self.textEdit_9.setObjectName("textEdit_9")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 390, 201, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(270, 390, 171, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.textEdit_24 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_24.setGeometry(QtCore.QRect(230, 60, 181, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_24.setFont(font)
        self.textEdit_24.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_24.setTabChangesFocus(True)
        self.textEdit_24.setUndoRedoEnabled(True)
        self.textEdit_24.setObjectName("textEdit_24")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_6.setGeometry(QtCore.QRect(440, 60, 181, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_6.setFont(font)
        self.textEdit_6.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_10.setGeometry(QtCore.QRect(20, 320, 601, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_10.setFont(font)
        self.textEdit_10.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_10.setObjectName("textEdit_10")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.toolBox = QtWidgets.QToolBox(self.tab_3)
        self.toolBox.setGeometry(QtCore.QRect(10, 20, 1011, 381))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet("")
        self.toolBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 1009, 199))
        self.page.setObjectName("page")
        self.label_28 = QtWidgets.QLabel(self.page)
        self.label_28.setGeometry(QtCore.QRect(10, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.textEdit_11 = QtWidgets.QTextEdit(self.page)
        self.textEdit_11.setGeometry(QtCore.QRect(10, 40, 991, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_11.setFont(font)
        self.textEdit_11.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_11.setObjectName("textEdit_11")
        self.toolBox.addItem(self.page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 1009, 199))
        self.page_3.setObjectName("page_3")
        self.label_31 = QtWidgets.QLabel(self.page_3)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.textEdit_12 = QtWidgets.QTextEdit(self.page_3)
        self.textEdit_12.setGeometry(QtCore.QRect(10, 30, 991, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_12.setFont(font)
        self.textEdit_12.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_12.setObjectName("textEdit_12")
        self.toolBox.addItem(self.page_3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 1009, 199))
        self.page_2.setObjectName("page_2")
        self.label_30 = QtWidgets.QLabel(self.page_2)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_33 = QtWidgets.QLabel(self.page_2)
        self.label_33.setGeometry(QtCore.QRect(10, 70, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.page_2)
        self.label_34.setGeometry(QtCore.QRect(10, 130, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.spinBox_4 = QtWidgets.QSpinBox(self.page_2)
        self.spinBox_4.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_4.setWhatsThis("")
        self.spinBox_4.setAccessibleName("")
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setMinimum(1917)
        self.spinBox_4.setMaximum(2060)
        self.spinBox_4.setProperty("value", 1917)
        self.spinBox_4.setObjectName("spinBox_4")
        self.textEdit_13 = QtWidgets.QTextEdit(self.page_2)
        self.textEdit_13.setGeometry(QtCore.QRect(10, 30, 991, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_13.setFont(font)
        self.textEdit_13.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_13.setObjectName("textEdit_13")
        self.textEdit_14 = QtWidgets.QTextEdit(self.page_2)
        self.textEdit_14.setGeometry(QtCore.QRect(10, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_14.setFont(font)
        self.textEdit_14.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_14.setObjectName("textEdit_14")
        self.toolBox.addItem(self.page_2, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 1009, 199))
        self.page_4.setObjectName("page_4")
        self.label_32 = QtWidgets.QLabel(self.page_4)
        self.label_32.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.textEdit_15 = QtWidgets.QTextEdit(self.page_4)
        self.textEdit_15.setGeometry(QtCore.QRect(10, 30, 991, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_15.setFont(font)
        self.textEdit_15.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_15.setObjectName("textEdit_15")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 1009, 199))
        self.page_5.setObjectName("page_5")
        self.label_35 = QtWidgets.QLabel(self.page_5)
        self.label_35.setGeometry(QtCore.QRect(10, 5, 171, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page_5)
        self.label_36.setGeometry(QtCore.QRect(10, 70, 201, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.textEdit_16 = QtWidgets.QTextEdit(self.page_5)
        self.textEdit_16.setGeometry(QtCore.QRect(10, 30, 991, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_16.setFont(font)
        self.textEdit_16.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_16.setObjectName("textEdit_16")
        self.textEdit_17 = QtWidgets.QTextEdit(self.page_5)
        self.textEdit_17.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_17.setFont(font)
        self.textEdit_17.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_17.setObjectName("textEdit_17")
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 1009, 199))
        self.page_6.setObjectName("page_6")
        self.label_38 = QtWidgets.QLabel(self.page_6)
        self.label_38.setGeometry(QtCore.QRect(10, 0, 171, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.textEdit_18 = QtWidgets.QTextEdit(self.page_6)
        self.textEdit_18.setGeometry(QtCore.QRect(10, 20, 991, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_18.setFont(font)
        self.textEdit_18.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_18.setObjectName("textEdit_18")
        self.toolBox.addItem(self.page_6, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(20, 370, 1001, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.pushButton_1 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 400, 101, 31))
        self.pushButton_1.setObjectName("pushButton_1")
        self.toolBox_2 = QtWidgets.QToolBox(self.tab_4)
        self.toolBox_2.setGeometry(QtCore.QRect(10, 10, 1021, 351))
        self.toolBox_2.setStyleSheet("")
        self.toolBox_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolBox_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 1019, 199))
        self.page_7.setObjectName("page_7")
        self.textEdit_19 = QtWidgets.QTextEdit(self.page_7)
        self.textEdit_19.setGeometry(QtCore.QRect(10, 0, 1001, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_19.setFont(font)
        self.textEdit_19.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_19.setObjectName("textEdit_19")
        self.toolBox_2.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 1019, 199))
        self.page_8.setObjectName("page_8")
        self.textEdit_20 = QtWidgets.QTextEdit(self.page_8)
        self.textEdit_20.setGeometry(QtCore.QRect(10, 10, 1001, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_20.setFont(font)
        self.textEdit_20.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_20.setObjectName("textEdit_20")
        self.toolBox_2.addItem(self.page_8, "")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 1019, 199))
        self.page_9.setObjectName("page_9")
        self.textEdit_21 = QtWidgets.QTextEdit(self.page_9)
        self.textEdit_21.setGeometry(QtCore.QRect(10, 10, 1001, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_21.setFont(font)
        self.textEdit_21.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_21.setObjectName("textEdit_21")
        self.toolBox_2.addItem(self.page_9, "")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 1019, 199))
        self.page_10.setObjectName("page_10")
        self.textEdit_22 = QtWidgets.QTextEdit(self.page_10)
        self.textEdit_22.setGeometry(QtCore.QRect(10, 10, 1001, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_22.setFont(font)
        self.textEdit_22.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_22.setObjectName("textEdit_22")
        self.toolBox_2.addItem(self.page_10, "")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setGeometry(QtCore.QRect(0, 0, 1019, 199))
        self.page_11.setObjectName("page_11")
        self.textEdit_23 = QtWidgets.QTextEdit(self.page_11)
        self.textEdit_23.setGeometry(QtCore.QRect(10, 10, 1001, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_23.setFont(font)
        self.textEdit_23.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_23.setObjectName("textEdit_23")
        self.toolBox_2.addItem(self.page_11, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 1041, 131))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(260, 100, 141, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(20, 60, 191, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox.setWhatsThis("")
        self.spinBox.setAccessibleName("")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setGeometry(QtCore.QRect(260, 60, 191, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.spinBox_2.setMouseTracking(False)
        self.spinBox_2.setTabletTracking(False)
        self.spinBox_2.setAccelerated(True)
        self.spinBox_2.setProperty("showGroupSeparator", False)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(5000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(260, 30, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 30, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 640, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(3)
        self.toolBox_2.setCurrentIndex(0)
        self.toolBox_2.layout().setSpacing(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.spinBox_3.setSpecialValueText(_translate("MainWindow", "----"))
        self.groupBox.setTitle(_translate("MainWindow", "Заводской номер"))
        self.label_15.setText(_translate("MainWindow", "Конец номера после изменяемой части"))
        self.label_12.setText(_translate("MainWindow", "Начало номера до изменяемой части"))
        self.label_14.setText(_translate("MainWindow", "Изменяемая часть номера"))
        self.textEdit_5.setWhatsThis(_translate("MainWindow", "Ввести начальное значение"))
        self.textEdit_4.setPlaceholderText(_translate("MainWindow", "Начальное значение"))
        self.label_4.setText(_translate("MainWindow", "Тип СИ (№ Гос. реестра)"))
        self.label_5.setText(_translate("MainWindow", "Модификация СИ"))
        self.label_6.setText(_translate("MainWindow", "Год выпуска"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Сведения о СИ"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_7.setText(_translate("MainWindow", "Условный шифр поверителя"))
        self.label_8.setText(_translate("MainWindow", "Дата поверки СИ"))
        self.label_13.setText(_translate("MainWindow", "Действительна до"))
        self.label_11.setText(_translate("MainWindow", "Методика поверки"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Номер свидетельства о поверке"))
        self.label_16.setText(_translate("MainWindow", "Начало номера до изменяемой части"))
        self.label_17.setText(_translate("MainWindow", "Изменяемая часть номера"))
        self.label_18.setText(_translate("MainWindow", "Конец номера после изменяемой части"))
        self.textEdit_8.setPlaceholderText(_translate("MainWindow", "Начальное значение"))
        self.checkBox.setText(_translate("MainWindow", "Знак поверки в паспорте"))
        self.checkBox_2.setText(_translate("MainWindow", "Знак поверки на СИ"))
        self.textEdit_24.setPlaceholderText(_translate("MainWindow", "ГГГГ-ММ-ДД"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Сведения о поверке"))
        self.label_28.setText(_translate("MainWindow", "№ ГПЭ по реестру"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Государственный первичный эталон"))
        self.label_31.setText(_translate("MainWindow", "№ эталона по реестру"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Эталон единицы величины"))
        self.label_30.setText(_translate("MainWindow", "№ типа СО по реестру"))
        self.label_33.setText(_translate("MainWindow", "Год выпуска"))
        self.label_34.setText(_translate("MainWindow", "Заводской №/№ партии"))
        self.spinBox_4.setSpecialValueText(_translate("MainWindow", "----"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Стандартные образцы, применяемые при поверке"))
        self.label_32.setText(_translate("MainWindow", "№ СИ по перечню"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "СИ, применяемое в качестве эталона"))
        self.label_35.setText(_translate("MainWindow", "Регистрационный № типа СИ"))
        self.label_36.setText(_translate("MainWindow", "Заводской номер/Инвентарный номер"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "СИ, применяемые при поверке"))
        self.label_38.setText(_translate("MainWindow", "Наименование, № по перечню"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "Вещество (материал), применяемое при поверке"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Средства поверки"))
        self.label_24.setText(_translate("MainWindow", "Приложите файл протокола поверки. Файл должен быть не более 1 Мб и одного из следующих типов: *.pdf, *.zip или формата MS Word"))
        self.pushButton_1.setText(_translate("MainWindow", "Загрузить"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), _translate("MainWindow", "Диапазоны (поддиапазоны) измерений, в которых поверено СИ"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_8), _translate("MainWindow", "Отдельные величины, для которых поверено СИ"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_9), _translate("MainWindow", "Измерительные каналы СИ, прошедшие поверку"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_10), _translate("MainWindow", "Отдельные автономные блоки из состава СИ, прошедшие поверку"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_11), _translate("MainWindow", "Прочие сведения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Прочие сведения"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Сведения о заявках"))
        self.label_3.setText(_translate("MainWindow", "Максимально 5000 записей"))
        self.label_2.setText(_translate("MainWindow", "Количество записей в одной заявке"))
        self.label.setText(_translate("MainWindow", "Общее количество записей"))
        self.pushButton.setText(_translate("MainWindow", "Создать заявки"))

